name: CFP template
description: Use this form to submit a CFP for a workshop, talk, or other session that you would like to host
title: "[CFP] : "
labels: ["CFP"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for being interested in hosting a session in the Polkadot Developer Heroes program! For more details and some examples please see the [CFPs repo Readme](https://github.com/Polkadot-Heroes/CFPs#readme).
        
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below as detailed as possible, the more information the better. In case something is missing, the reviewers will leave a comment on the issue and await your response or edit if needed. 
        
  - type: textarea
    id: CFP-speakers-information
    attributes:
      label: Speaker(s) Information
      description: Include names of the speaker(s). Provide credentials and short descriptions for each speaker to establish expertise and relevance.
      placeholder: Add speaker(s) information here.
      
  - type: textarea
    id: CFP-session-time-and-duration
    attributes:
      label: Time and Duration of the Session
      description: Propose a time and duration for the session at least two weeks in advance. Check the [events calendar]((https://www.notion.so/polkadotheroes/Workshops-Events-003b8a739a1b496f9bcb1f36ddd2aa3f) for slot availability. If proposing a series, provide multiple times, dates and durations.
      placeholder: Add session time(s) and duration(s) here.

  - type: textarea
    id: CFP-session-format
    attributes:
      label: Format of the Session
      description: Clearly define the format (e.g., workshop, panel discussion, hackathon). For ideas refer back to the [Scope and formats section of the Readme](https://github.com/Polkadot-Heroes/CFPs#scope-and-formats). If proposing a series of multiple sessions, make sure to define the format of each session.  
      placeholder: Add format(s) here.

  - type: textarea
    id: CFP-session-description
    attributes:
      label: Detailed Description
      description: Provide an engaging and informative description of your session, which we can use in communication to members (e.g. during community calls and emails). Include an agenda and detailed breakdown for each session, especially if proposing multiple sessions.
      placeholder: Add description(s).

  - type: textarea
    id: CFP-session-prerequisits
    attributes:
      label: Prerequisites
      description: Explain how participants should prepare for the session as well as detail any materials, resources, or tools participants will need including any technical requirements or infrastructure.
      placeholder: Add prerequisits.
